compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - win32
    - linux

yarnPath: .yarn/releases/yarn-4.9.2-git.20250630.hash-8598d07.cjs
